Log post
oslabs-beta/Sherlogs pull request #30
Opened 2022-02-18 03:02 UTC by felisity09

Wrote an express middleware to store log into the database

2022-02-18 03:57 UTC, Agfeynman requested changes
Nice job Felicity!!!. I made some suggestions. Also you need to remove all the 'working' commit messages and put a semantic message instead. That's important in case we have some problem in the future and we want to go back or if we want to create a changelog using a tool which is probable.

2022-02-18 03:57 UTC, Agfeynman commented on server/controllers/logController.js
> +    // TODO: able to store more than one log
Pls remove the comment. We need a different controller for that

2022-02-18 03:57 UTC, Agfeynman commented on server/controllers/logController.js
> +      console.log('missing log');
You want to use the logger for log the error server side and the error handler to send the information to the client.

2022-02-18 03:57 UTC, Agfeynman commented on server/routes/v1.routes.js
> +    message: 'storeLog middleware: Successfully stored log into DB',
Can you remove the storeLog middleware from here. The client doesn't want to know that detail implementation.

2022-02-20 17:03 UTC, velveteen-ant approved these changes
approving -- I saw working test during live share session. I agree on also using more descriptive commit messages

2022-02-20 22:02 UTC, merged